### ISSUE TITLE
HTTP 5xx errors stat is buggy

### ISSUE THREAD

**Issue by hvelarde** [nginxinc/nginx-amplify-agent#69]
The comparison stats shown for HTTP 5xx errors on daily basis makes no sense:

![selection_023](https://user-images.githubusercontent.com/341393/29876464-3aa543e8-8d73-11e7-895c-0cc307c2a5ea.png)

**Comment by hvelarde** [comment]
Another example from today:

![selection_023](https://user-images.githubusercontent.com/341393/29876607-ae3fc954-8d73-11e7-82ce-8ec8634f8a28.png)

**Comment by ptreyes** [comment]
Hi,

Thanks for sharing this! The formula seems to be quite right though. Do you mean, with that much difference between the number of 5xx errors in your particular case, you don't see much value in the stats above?

Also, curious why do you have that many 5xx one day, and way less the other day?

Many thanks!

**Comment by hvelarde** [comment]
that's the point: we don't have such high/low number of 5xx errors; that's a bug in Amplify.

typically we have around 2.000 HTTP 5xx errors every day.

**Comment by ptreyes** [comment]
Ouch, apologies for misinterpreting the above! Can you please reach out through the Intercom chat in the UI, providing all the details about the time period in question, the exact system/nginx you're observing this for and other details? That would be greatly appreciated, and we'll make sure to resolve this. Thanks for reporting it!

**Comment by hvelarde** [comment]
I can't find that option in the UI; I sent a message a couple of days ago to Eugene about this.

**Comment by ptreyes** [comment]
As a quick update - we've been trying to isolate this for analysis, but can't reproduce it reliably. Can I ask you to ping us once again if you see anything like the above (an incorrect number of "previous" period 5xx errors)? That would be really appreciated! Also, the "Intercom" chat button is in the right bottom corner of the UI :)

**Comment by hvelarde** [comment]
seems to be fixed now, if I see it again I'll reopen this ticket; BTW, I don't find the intercom chat button: it will be nice to attach a screen shot.

**Comment by hvelarde** [comment]
I keep seeing this strange behavior; it happens only on the statistics o the past day as you can see below.

previous day marks 433k 5xx errors, which is obviously wrong:
![screenshot-2017-9-26 nginx monitoring made easy 2](https://user-images.githubusercontent.com/341393/30884140-d716c54a-a2e4-11e7-9741-71820a6b3e54.png)

if I select past 2 days, the behavior is correct (1k 5xx errors):
![screenshot-2017-9-26 nginx monitoring made easy 3](https://user-images.githubusercontent.com/341393/30884163-eeb9b680-a2e4-11e7-9eef-55080957d7bf.png)

**Comment by gshulegaard** [comment]
Hi @hvelarde ... so it seems the graphs are correct but the calculation for the previous reported value is inaccurate?

**Comment by hvelarde** [comment]
yes, indeed.

**Comment by gshulegaard** [comment]
Thanks!  I will put this on my TODO list.  I'll check back in to let you know if I find anything obvious.

**Comment by gshulegaard** [comment]
Hi @hvelarde, just wanted to let you know that I took a closer look and discovered that these values are being calculated on our Frontend side.  I will escalate to our Frontend group.

**Comment by gshulegaard** [comment]
Hi @hvelarde, just wanted to let you know that I took a closer look and discovered that these values are being calculated on our Frontend side.  I will escalate to our Frontend group.

**Comment by imeleschenko** [comment]
Hello @hvelarde,
Sorry for the long time response.

There are two problems here:
1. Wrong previous value - should be fixed now. Could you check it please?
When you closed this issue before, we hadn't fixed it. I think you just got another values with similar multiplier (e.g. 1K and 2K, 300 and 60).
2. Wrong delta calculating - will be fixed within the next release. I'll let you know.

And many thanks for the report, really appreciate it.

P.S.: If the thing with Intercom button is still actual, please, check the screenshot below:

![image](https://user-images.githubusercontent.com/3491165/33136505-702c2e84-cfb6-11e7-852b-f29d69748e42.png)

That black circle on the right bottom. There could be problems, if you use some adblock tool.

**Comment by hvelarde** [comment]
thanks, seems we still have some issues as you can see:

![screenshot-2017-11-22 nginx monitoring made easy](https://user-images.githubusercontent.com/341393/33139662-1a49b822-cf95-11e7-8000-8206a797c14d.png)

I disabled the ad blocker for your site and now I see the feedback button.

**Comment by imeleschenko** [comment]
The one with delta (-100%) **will** be fixed within the next release. It should be around +12%.
Or you talking about "Previous" value? Is it wrong?

**Comment by imeleschenko** [comment]
Hi @hvelarde,
We've fixed the "wrong delta" issue. Please, check if your Overview board is well now.
